
name: docs_pages_workflow

# Execute this workflow automatically when pushing to master
on:
  push:
    branches: [master]
        
jobs:
  build_doc_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    
    steps:
    
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
      
    - name: Execute script to build our documenation and update pages
      run: "docs/buildDocs.sh"
      shell: bash
        